#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB9069B1335700CDC (infra-root@openstack.org)
#
Name     : openstack-doc-tools
Version  : 1.5.0
Release  : 40
URL      : http://tarballs.openstack.org/openstack-doc-tools/openstack-doc-tools-1.5.0.tar.gz
Source0  : http://tarballs.openstack.org/openstack-doc-tools/openstack-doc-tools-1.5.0.tar.gz
Source99 : http://tarballs.openstack.org/openstack-doc-tools/openstack-doc-tools-1.5.0.tar.gz.asc
Summary  : Tools for OpenStack Documentation
Group    : Development/Tools
License  : Apache-2.0
Requires: openstack-doc-tools-bin
Requires: openstack-doc-tools-python
Requires: openstack-doc-tools-data
Requires: Jinja2
Requires: PyYAML
Requires: Sphinx
Requires: cliff-tablib
Requires: demjson
Requires: docutils
Requires: iso8601
Requires: lxml
Requires: oslo.config
Requires: oslo.i18n
Requires: pbr
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/openstack-doc-tools.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package bin
Summary: bin components for the openstack-doc-tools package.
Group: Binaries
Requires: openstack-doc-tools-data

%description bin
bin components for the openstack-doc-tools package.


%package data
Summary: data components for the openstack-doc-tools package.
Group: Data

%description data
data components for the openstack-doc-tools package.


%package python
Summary: python components for the openstack-doc-tools package.
Group: Default

%description python
python components for the openstack-doc-tools package.


%prep
%setup -q -n openstack-doc-tools-1.5.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490890301
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1490890301
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/doc-tools-build-rst
/usr/bin/doc-tools-check-languages
/usr/bin/doc-tools-update-cli-reference
/usr/bin/openstack-auto-commands
/usr/bin/openstack-indexpage
/usr/bin/openstack-jsoncheck

%files data
%defattr(-,root,root,-)
/usr/share/openstack-doc-tools/cleanup/prettify.py
/usr/share/openstack-doc-tools/cleanup/prettify.pyc
/usr/share/openstack-doc-tools/cleanup/prettify.pyo
/usr/share/openstack-doc-tools/cleanup/remove_trailing_whitespaces.sh
/usr/share/openstack-doc-tools/cleanup/remove_unnecessary_spaces.py
/usr/share/openstack-doc-tools/cleanup/remove_unnecessary_spaces.pyc
/usr/share/openstack-doc-tools/cleanup/remove_unnecessary_spaces.pyo
/usr/share/openstack-doc-tools/cleanup/retf/README.md
/usr/share/openstack-doc-tools/cleanup/retf/disabled_rules.yaml
/usr/share/openstack-doc-tools/cleanup/retf/retf.py
/usr/share/openstack-doc-tools/cleanup/retf/retf.pyc
/usr/share/openstack-doc-tools/cleanup/retf/retf.pyo
/usr/share/openstack-doc-tools/sitemap/README.rst
/usr/share/openstack-doc-tools/sitemap/__init__.py
/usr/share/openstack-doc-tools/sitemap/__init__.pyc
/usr/share/openstack-doc-tools/sitemap/__init__.pyo
/usr/share/openstack-doc-tools/sitemap/generator/__init__.py
/usr/share/openstack-doc-tools/sitemap/generator/__init__.pyc
/usr/share/openstack-doc-tools/sitemap/generator/__init__.pyo
/usr/share/openstack-doc-tools/sitemap/generator/pipelines.py
/usr/share/openstack-doc-tools/sitemap/generator/pipelines.pyc
/usr/share/openstack-doc-tools/sitemap/generator/pipelines.pyo
/usr/share/openstack-doc-tools/sitemap/generator/settings.py
/usr/share/openstack-doc-tools/sitemap/generator/settings.pyc
/usr/share/openstack-doc-tools/sitemap/generator/settings.pyo
/usr/share/openstack-doc-tools/sitemap/generator/spiders/__init__.py
/usr/share/openstack-doc-tools/sitemap/generator/spiders/__init__.pyc
/usr/share/openstack-doc-tools/sitemap/generator/spiders/__init__.pyo
/usr/share/openstack-doc-tools/sitemap/generator/spiders/sitemap_file.py
/usr/share/openstack-doc-tools/sitemap/generator/spiders/sitemap_file.pyc
/usr/share/openstack-doc-tools/sitemap/generator/spiders/sitemap_file.pyo
/usr/share/openstack-doc-tools/sitemap/requirements.txt
/usr/share/openstack-doc-tools/sitemap/scrapy.cfg
/usr/share/openstack-doc-tools/sitemap/test/__init__.py
/usr/share/openstack-doc-tools/sitemap/test/__init__.pyc
/usr/share/openstack-doc-tools/sitemap/test/__init__.pyo
/usr/share/openstack-doc-tools/sitemap/test/generator/spiders/test_sitemap_file.py
/usr/share/openstack-doc-tools/sitemap/test/generator/spiders/test_sitemap_file.pyc
/usr/share/openstack-doc-tools/sitemap/test/generator/spiders/test_sitemap_file.pyo
/usr/share/openstack-doc-tools/sitemap/test/generator/test_items.py
/usr/share/openstack-doc-tools/sitemap/test/generator/test_items.pyc
/usr/share/openstack-doc-tools/sitemap/test/generator/test_items.pyo
/usr/share/openstack-doc-tools/sitemap/test/generator/test_pipelines.py
/usr/share/openstack-doc-tools/sitemap/test/generator/test_pipelines.pyc
/usr/share/openstack-doc-tools/sitemap/test/generator/test_pipelines.pyo
/usr/share/openstack-doc-tools/sitemap/transform-sitemap.xslt

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
